export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_CLIENT_ID = 'SET_CLIENT_ID';
export const SET_EMAIL_ADDRESS = 'SET_EMAIL_ADDRESS';
export const SET_BACKEND = 'SET_BACKEND';
export const SET_COMPUTE = 'SET_COMPUTE';
