export const START_WPS_EXECUTE_START = 'START_WPS_EXECUTE_START';
export const START_WPS_EXECUTE_FAILED = 'START_WPS_EXECUTE_FAILED';
export const START_WPS_EXECUTE_END = 'START_WPS_EXECUTE_END';
export const WPS_STATUS_UPDATE = 'WPS_STATUS_UPDATE';
export const WPS_COMPLETED = 'WPS_COMPLETED';
export const SET_CSV_FILE_TO_WRANGLE = 'SET_CSV_FILE_TO_WRANGLE';
